#include "metrolink_map.h"

const char *METROLINK_STATIONS[] = {
	"Abraham Moss",
	"Altrincham",
	"Anchorage",
	"Ashton Moss",
	"Ashton-Under-Lyne",
	"Ashton West",
	"Audenshaw",
	"Baguley",
	"Barlow Moor Road",
	"Benchill",
	"Besses O’ Th’ Barn",
	"Bowker Vale",
	"Broadway",
	"Brooklands",
	"Burton Road",
	"Bury",
	"Cemetery Road",
	"Central Park",
	"Chorlton",
	"Clayton Hall",
	"Cornbrook",
	"Crossacres",
	"Crumpsall",
	"Dane Road",
	"Deansgate - Castlefield",
	"Derker",
	"Didsbury Village",
	"Droylsden",
	"East Didsbury",
	"Eccles",
	"Edge Lane",
	"Etihad Campus",
	"Exchange Quay",
	"Exchange Square",
	"Failsworth",
	"Firswood",
	"Freehold",
	"Harbour City",
	"Heaton Park",
	"Hollinwood",
	"Holt Town",
	"Kingsway Business Park",
	"Ladywell",
	"Langworthy",
	"Manchester Airport",
	"Market Street",
	"Martinscroft",
	"MediaCityUK",
	"Milnrow",
	"Monsall",
	"Moor Road",
	"Navigation Road",
	"Newbold",
	"Newhey",
	"New Islington",
	"Newton Heath and Moston",
	"Northern Moor",
	"Oldham Central",
	"Oldham King Street",
	"Oldham Mumps",
	"Old Trafford",
	"Peel Hall",
	"Piccadilly",
	"Piccadilly Gardens",
	"Pomona",
	"Prestwich",
	"Queens Road",
	"Radcliffe",
	"Robinswood Road",
	"Rochdale Railway Station",
	"Rochdale Town Centre",
	"Roundthorn",
	"Sale",
	"Sale Water Park",
	"Salford Quays",
	"Shadowmoss",
	"Shaw and Crompton",
	"Shudehill",
	"South Chadderton",
	"St Peters Square",
	"Stretford",
	"St Werburgh’s Road",
	"Timperley",
	"Trafford Bar",
	"Velopark",
	"Victoria",
	"Weaste",
	"West Didsbury",
	"Westwood",
	"Whitefield",
	"Withington",
	"Wythenshawe Park",
	"Wythenshawe Town Centre",
};

/**
 * The number of Metrolink stations.
 */
size_t NUM_METROLINK_STATIONS = sizeof(METROLINK_STATIONS)/sizeof(METROLINK_STATIONS[0]);

/**
 * Lists (for one direction only) connections between stations.
 */
metrolink_name_pair_t METROLINK_LINKS[] = {
	// Eccles line
	{"Eccles", "Ladywell"},
	{"Ladywell", "Weaste"},
	{"Weaste", "Langworthy"},
	{"Langworthy", "Broadway"},
	{"Broadway", "MediaCityUK"},
	{"Broadway", "Harbour City"},
	{"MediaCityUK", "Harbour City"},
	{"Harbour City", "Anchorage"},
	{"Anchorage", "Salford Quays"},
	{"Salford Quays", "Exchange Quay"},
	{"Exchange Quay", "Pomona"},
	{"Pomona", "Cornbrook"},
	
	// Altrincham line
	{"Altrincham", "Navigation Road"},
	{"Navigation Road", "Timperley"},
	{"Timperley", "Brooklands"},
	{"Brooklands", "Sale"},
	{"Sale", "Dane Road"},
	{"Dane Road", "Stretford"},
	{"Stretford", "Old Trafford"},
	{"Old Trafford", "Trafford Bar"},
	{"Trafford Bar", "Cornbrook"},
	
	// Manchester Airport line
	{"Manchester Airport", "Shadowmoss"},
	{"Shadowmoss", "Peel Hall"},
	{"Peel Hall", "Robinswood Road"},
	{"Robinswood Road", "Wythenshawe Town Centre"},
	{"Wythenshawe Town Centre", "Crossacres"},
	{"Crossacres", "Benchill"},
	{"Benchill", "Martinscroft"},
	{"Martinscroft", "Roundthorn"},
	{"Roundthorn", "Baguley"},
	{"Baguley", "Moor Road"},
	{"Moor Road", "Wythenshawe Park"},
	{"Wythenshawe Park", "Northern Moor"},
	{"Northern Moor", "Sale Water Park"},
	{"Sale Water Park", "Barlow Moor Road"},
	{"Barlow Moor Road", "St Werburgh’s Road"},
	{"St Werburgh’s Road", "Chorlton"},
	{"Chorlton", "Firswood"},
	{"Firswood", "Trafford Bar"},
	
	// East Didsbury line
	{"East Didsbury", "Didsbury Village"},
	{"Didsbury Village", "West Didsbury"},
	{"West Didsbury", "Burton Road"},
	{"Burton Road", "Withington"},
	{"Withington", "St Werburgh’s Road"},
	
	// Bits of the city center
	{"Cornbrook", "Deansgate - Castlefield"},
	{"Deansgate - Castlefield", "St Peters Square"},
	{"St Peters Square", "Exchange Square"},
	{"Exchange Square", "Victoria"},
	
	{"St Peters Square", "Market Street"},
	{"Market Street", "Shudehill"},
	{"Shudehill", "Victoria"},
	
	{"St Peters Square", "Piccadilly Gardens"},
	{"Piccadilly Gardens", "Market Street"},
	{"Piccadilly Gardens", "Piccadilly"},
	{"Piccadilly", "New Islington"},
	
	// Bury line
	{"Bury", "Radcliffe"},
	{"Radcliffe", "Whitefield"},
	{"Whitefield", "Besses O’ Th’ Barn"},
	{"Besses O’ Th’ Barn", "Prestwich"},
	{"Prestwich", "Heaton Park"},
	{"Heaton Park", "Bowker Vale"},
	{"Bowker Vale", "Crumpsall"},
	{"Crumpsall", "Abraham Moss"},
	{"Abraham Moss", "Queens Road"},
	{"Queens Road", "Victoria"},
	
	// Rochdale line
	{"Rochdale Town Centre", "Rochdale Railway Station"},
	{"Rochdale Railway Station", "Newbold"},
	{"Newbold", "Kingsway Business Park"},
	{"Kingsway Business Park", "Milnrow"},
	{"Milnrow", "Newhey"},
	{"Newhey", "Shaw and Crompton"},
	{"Shaw and Crompton", "Derker"},
	{"Derker", "Oldham Mumps"},
	{"Oldham Mumps", "Oldham Central"},
	{"Oldham Central", "Oldham King Street"},
	{"Oldham King Street", "Westwood"},
	{"Westwood", "Freehold"},
	{"Freehold", "South Chadderton"},
	{"South Chadderton", "Hollinwood"},
	{"Hollinwood", "Failsworth"},
	{"Failsworth", "Newton Heath and Moston"},
	{"Newton Heath and Moston", "Central Park"},
	{"Central Park", "Monsall"},
	{"Monsall", "Victoria"},
	
	// Ashton line
	{"Ashton-Under-Lyne", "Ashton West"},
	{"Ashton West", "Ashton Moss"},
	{"Ashton Moss", "Audenshaw"},
	{"Audenshaw", "Droylsden"},
	{"Droylsden", "Cemetery Road"},
	{"Cemetery Road", "Edge Lane"},
	{"Edge Lane", "Clayton Hall"},
	{"Clayton Hall", "Velopark"},
	{"Velopark", "Etihad Campus"},
	{"Etihad Campus", "Holt Town"},
	{"Holt Town", "New Islington"},
};

/**
 * Number of entries in METROLINK_LINKS.
 */
size_t NUM_METROLINK_LINKS = sizeof(METROLINK_LINKS)/sizeof(METROLINK_LINKS[0]);

